server:
  port: 8088
spring:
  datasource:
    initialize: true
    url: jdbc:mysql://localhost:3306/reddit-clone-db?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
