server:
  port: 8088
spring:
  datasource:
    initialize: true
    url: jdbc:mysql://localhost:3306/reddit-clone-db?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 2f4b92181b4eb7
    password: 751e9d270b2950
    protocol: smtp
    ### THIS IS STRICTLY FOR DEMO PURPOSE ONLY. ###
jwt:
  expiration:
    time: 90000
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key